name: hyper_pay_payment
description: "HYPER PAY FLUTTER PLUGIN , Payment method : VISA, MASTER, MADA, APPLE PAY"
version: 1.0.3
homepage: https://www.hyperpay.com
repository: https://github.com/AbdallahDafa/hyper_pay_flutter_plugin
license: MIT


environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^0.5.1
  plugin_platform_interface: ^2.0.2


  #----------------------------- cas flutter need to run ios example project as application
  hyper_pay_payment_example:
    path: example


#----------------------------- cas flutter plugin when publish uncomment this code

flutter:
  plugin:
    platforms:
      android:
        package: com.dafa.hyperpay.hyper_pay
        pluginClass: HyperPayPlugin
      ios:
        pluginClass: HyperPayPlugin
        platformVersion: '15.0'  # or your desired minimum iOS version
#      web:
#        pluginClass: HyperPayWeb
#        fileName: hyper_pay_web.dart
