name: hyper_pay_payment
description: "HYPER PAY FLUTTER PLUGIN , Payment method : VISA, MASTER, MADA, APPLE PAY"
version: 1.0.20
homepage: https://www.hyperpay.com
repository: https://github.com/AbdallahDafa/hyper_pay_flutter_plugin
license: Copyright © 2025 MASARAT Company. All rights reserved


environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.1.0
  plugin_platform_interface: ^2.1.8


  #----------------------------- this code may needed in run on xcode
#  hyper_pay_payment_example:
#    path: example

flutter:
  plugin:
    platforms:
      android:
        package: com.dafa.hyperpay.hyper_pay
        pluginClass: HyperPayPlugin
      ios:
        pluginClass: HyperPayPlugin
        platformVersion: '13.0'  # or your desired minimum iOS version
#      web:
#        pluginClass: HyperPayWeb
#        fileName: hyper_pay_web.dart
